// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPull() {
  return window['go']['main']['App']['CancelPull']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function LoadModel(arg1) {
  return window['go']['main']['App']['LoadModel'](arg1);
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function PullModelWithProgress(arg1) {
  return window['go']['main']['App']['PullModelWithProgress'](arg1);
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}
