// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelPull():Promise<string>;

export function GetSetupStatus():Promise<string>;

export function GetStatus():Promise<main.ServerStatus>;

export function ListModels():Promise<Array<string>>;

export function LoadModel(arg1:string):Promise<void>;

export function PullModel(arg1:string):Promise<string>;

export function PullModelWithProgress(arg1:string):Promise<string>;

export function RunCommand(arg1:string):Promise<string>;

export function SendMessage(arg1:string):Promise<string>;
